### ISSUE TITLE
Cannot find module 'nock' from 'index.js'

### ISSUE THREAD

**Issue by moltar** [spring-media/jest-nock#2]
Hey,

I'm getting the following error, when trying to use this module:

```
❯ npx jest
 FAIL  test/file.test.ts
  ● Test suite failed to run

    Cannot find module 'nock' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:203:17)
      at Object.<anonymous> (node_modules/jest-nock/index.js:7:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.567s
Ran all test suites.
```

**Comment by moltar** [comment]
Oh, right, it's a peer dep. Would be good to document it, even with just the install command `yarn add jest-nock nock`
